version: "3.9"

services:
  babys-first-web-app:
    image: babys-first-web-app:latest
    env_file:
      - ./babys-first-web-app/babys-first-web-app.env
    expose:
      - "5000"
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: